name: setup

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install required build tools
        run: |
          apt-get update
          apt-get install -y build-essentials protobuf-compiler
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
