name: setup

description: Setsup all of the project dependancies

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install required build tools (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential protobuf-compiler protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: Install required build tools (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install protoc
        go install google.golang.org/protobuf/cmd/protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: Install required build tools (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install protobuf
        go install google.golang.org/protobuf/cmd/protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
