// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.5
// source: settings.proto

package pb_settings

import (
	context "context"
	pb_common "github.com/djpiper28/rpg-book/desktop_client/backend/pb_common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingsSvc_GetSettings_FullMethodName = "/SettingsSvc/GetSettings"
)

// SettingsSvcClient is the client API for SettingsSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsSvcClient interface {
	GetSettings(ctx context.Context, in *pb_common.Empty, opts ...grpc.CallOption) (*Settings, error)
}

type settingsSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsSvcClient(cc grpc.ClientConnInterface) SettingsSvcClient {
	return &settingsSvcClient{cc}
}

func (c *settingsSvcClient) GetSettings(ctx context.Context, in *pb_common.Empty, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, SettingsSvc_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsSvcServer is the server API for SettingsSvc service.
// All implementations must embed UnimplementedSettingsSvcServer
// for forward compatibility.
type SettingsSvcServer interface {
	GetSettings(context.Context, *pb_common.Empty) (*Settings, error)
	mustEmbedUnimplementedSettingsSvcServer()
}

// UnimplementedSettingsSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingsSvcServer struct{}

func (UnimplementedSettingsSvcServer) GetSettings(context.Context, *pb_common.Empty) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedSettingsSvcServer) mustEmbedUnimplementedSettingsSvcServer() {}
func (UnimplementedSettingsSvcServer) testEmbeddedByValue()                     {}

// UnsafeSettingsSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsSvcServer will
// result in compilation errors.
type UnsafeSettingsSvcServer interface {
	mustEmbedUnimplementedSettingsSvcServer()
}

func RegisterSettingsSvcServer(s grpc.ServiceRegistrar, srv SettingsSvcServer) {
	// If the following call pancis, it indicates UnimplementedSettingsSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingsSvc_ServiceDesc, srv)
}

func _SettingsSvc_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsSvcServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsSvc_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsSvcServer).GetSettings(ctx, req.(*pb_common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsSvc_ServiceDesc is the grpc.ServiceDesc for SettingsSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SettingsSvc",
	HandlerType: (*SettingsSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSettings",
			Handler:    _SettingsSvc_GetSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settings.proto",
}
