package main

import (
	"fmt"
	"os"

	"github.com/charmbracelet/log"
)

const notice = "// exports generated by ./post_process_pbs.go"

func handleFile(filename string) error {
	log.Info("Processing js protobuf", "filename", filename)
	dataB, err := os.ReadFile(filename)
	if err != nil {
		return err
	}

	data := string(dataB) + fmt.Sprintf(`}

%s
module.exports = proto;
`, notice)

	err = os.WriteFile(filename, []byte(data), 0777)
	return err
}

func main() {
	for _, filename := range os.Args[1:] {
		if err := handleFile(filename); err != nil {
			log.Fatal("Cannot run post-processing script", "file", filename, "error", err)
		}
	}
}
