/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.5
// source: system.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as common_pb from './common_pb'; // proto import: "common.proto"
import * as system_pb from './system_pb'; // proto import: "system.proto"


export class SystemSvcClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetSettings = new grpcWeb.MethodDescriptor(
    '/SystemSvc/GetSettings',
    grpcWeb.MethodType.UNARY,
    common_pb.Empty,
    system_pb.Settings,
    (request: common_pb.Empty) => {
      return request.serializeBinary();
    },
    system_pb.Settings.deserializeBinary
  );

  getSettings(
    request: common_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<system_pb.Settings>;

  getSettings(
    request: common_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: system_pb.Settings) => void): grpcWeb.ClientReadableStream<system_pb.Settings>;

  getSettings(
    request: common_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: system_pb.Settings) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/SystemSvc/GetSettings',
        request,
        metadata || {},
        this.methodDescriptorGetSettings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/SystemSvc/GetSettings',
    request,
    metadata || {},
    this.methodDescriptorGetSettings);
  }

  methodDescriptorLog = new grpcWeb.MethodDescriptor(
    '/SystemSvc/Log',
    grpcWeb.MethodType.UNARY,
    system_pb.LogRequest,
    common_pb.Empty,
    (request: system_pb.LogRequest) => {
      return request.serializeBinary();
    },
    common_pb.Empty.deserializeBinary
  );

  log(
    request: system_pb.LogRequest,
    metadata?: grpcWeb.Metadata | null): Promise<common_pb.Empty>;

  log(
    request: system_pb.LogRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: common_pb.Empty) => void): grpcWeb.ClientReadableStream<common_pb.Empty>;

  log(
    request: system_pb.LogRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: common_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/SystemSvc/Log',
        request,
        metadata || {},
        this.methodDescriptorLog,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/SystemSvc/Log',
    request,
    metadata || {},
    this.methodDescriptorLog);
  }

}

