package parser

// Code generated by /home/danny/.cache/go-build/e3/e3696674d794f79e14a8e853c800d82703f8baf09bdb1607a320a2d21ea54ee5-d/peg -strict -inline -switch ./query.peg DO NOT EDIT.

import (
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleGrammar
	ruleQuery
	ruleTerm
	ruleTextQuery
	ruleSetGenerator
	ruleBinaryOperator
	ruleGeneratorBinaryOperator
	ruleSpacing
	ruleQuotedText
	ruleText
	ruleEndOfFile
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
	ruleAction7
	ruleAction8
	ruleAction9
	ruleAction10
	ruleAction11
	ruleAction12
	ruleAction13
	ruleAction14
	ruleAction15
	ruleAction16
	ruleAction17
	ruleAction18
	ruleAction19
	rulePegText
	ruleAction20
	ruleAction21
)

var rul3s = [...]string{
	"Unknown",
	"Grammar",
	"Query",
	"Term",
	"TextQuery",
	"SetGenerator",
	"BinaryOperator",
	"GeneratorBinaryOperator",
	"Spacing",
	"QuotedText",
	"Text",
	"EndOfFile",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
	"Action7",
	"Action8",
	"Action9",
	"Action10",
	"Action11",
	"Action12",
	"Action13",
	"Action14",
	"Action15",
	"Action16",
	"Action17",
	"Action18",
	"Action19",
	"PegText",
	"Action20",
	"Action21",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type parser struct {
	tempNode *Node
	stack    []*Node
	Err      error

	Buffer string
	buffer []rune
	rules  [35]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func (p *parser) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, token := range p.Tokens() {
		switch token.pegRule {

		case rulePegText:
			begin, end = int(token.begin), int(token.end)
			text = string(_buffer[begin:end])

		case ruleAction0:
			p.insertOperatorNode()
		case ruleAction1:
			p.push(p.finaliseStack())
		case ruleAction2:
			p.tempNode.BinaryOperator = Default_BinaryOperator
			p.insertOperatorNode()
		case ruleAction3:
			p.push(p.finaliseStack())
		case ruleAction4:
			p.tempNode.Type = NodeType_SetGenerator
			p.tempNode.SetGenerator.Negated = true
		case ruleAction5:
			p.tempNode.Type = NodeType_SetGenerator
		case ruleAction6:
			p.tempNode.Type = NodeType_Basic
			p.tempNode.BasicQuery.Value = text
		case ruleAction7:
			p.push(p.tempNode)
		case ruleAction8:
			p.push(p.finaliseStack())
		case ruleAction9:
			p.tempNode.SetGenerator.Key = text
		case ruleAction10:
			p.tempNode.SetGenerator.Value = text
		case ruleAction11:
			p.tempNode.BinaryOperator = BinaryOperator_Or
		case ruleAction12:
			p.tempNode.BinaryOperator = BinaryOperator_And
		case ruleAction13:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_Includes
		case ruleAction14:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_LessThanEquals
		case ruleAction15:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_LessThan
		case ruleAction16:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_GreaterThanEquals
		case ruleAction17:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_GreaterThan
		case ruleAction18:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_Equals
		case ruleAction19:
			p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_NotEquals
		case ruleAction20:

			output, err := UnescapeText(text)
			if err != nil {
				p.Err = errors.Join(fmt.Errorf("Cannot parse quoted string '%s'", text))
				return
			}

			text = NormText(output)

		case ruleAction21:
			text = NormText(text)

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty(pretty bool) func(*parser) error {
	return func(p *parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*parser) error {
	return func(p *parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *parser) Init(options ...func(*parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Grammar <- <(Spacing? Query Spacing? EndOfFile)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2, tokenIndex2 := position, tokenIndex
					if !_rules[ruleSpacing]() {
						goto l2
					}
					goto l3
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
			l3:
				if !_rules[ruleQuery]() {
					goto l0
				}
				{
					position4, tokenIndex4 := position, tokenIndex
					if !_rules[ruleSpacing]() {
						goto l4
					}
					goto l5
				l4:
					position, tokenIndex = position4, tokenIndex4
				}
			l5:
				{
					position6 := position
					{
						position7, tokenIndex7 := position, tokenIndex
						if !matchDot() {
							goto l7
						}
						goto l0
					l7:
						position, tokenIndex = position7, tokenIndex7
					}
					add(ruleEndOfFile, position6)
				}
				add(ruleGrammar, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Query <- <((Term Spacing BinaryOperator Action0 Spacing Query Action1) / (Term Spacing Action2 Query Action3) / Term)> */
		func() bool {
			position8, tokenIndex8 := position, tokenIndex
			{
				position9 := position
				{
					position10, tokenIndex10 := position, tokenIndex
					if !_rules[ruleTerm]() {
						goto l11
					}
					if !_rules[ruleSpacing]() {
						goto l11
					}
					{
						position12 := position
						{
							position13, tokenIndex13 := position, tokenIndex
							if buffer[position] != rune('o') {
								goto l14
							}
							position++
							if buffer[position] != rune('r') {
								goto l14
							}
							position++
							{
								add(ruleAction11, position)
							}
							goto l13
						l14:
							position, tokenIndex = position13, tokenIndex13
							if buffer[position] != rune('a') {
								goto l11
							}
							position++
							if buffer[position] != rune('n') {
								goto l11
							}
							position++
							if buffer[position] != rune('d') {
								goto l11
							}
							position++
							{
								add(ruleAction12, position)
							}
						}
					l13:
						add(ruleBinaryOperator, position12)
					}
					{
						add(ruleAction0, position)
					}
					if !_rules[ruleSpacing]() {
						goto l11
					}
					if !_rules[ruleQuery]() {
						goto l11
					}
					{
						add(ruleAction1, position)
					}
					goto l10
				l11:
					position, tokenIndex = position10, tokenIndex10
					if !_rules[ruleTerm]() {
						goto l19
					}
					if !_rules[ruleSpacing]() {
						goto l19
					}
					{
						add(ruleAction2, position)
					}
					if !_rules[ruleQuery]() {
						goto l19
					}
					{
						add(ruleAction3, position)
					}
					goto l10
				l19:
					position, tokenIndex = position10, tokenIndex10
					if !_rules[ruleTerm]() {
						goto l8
					}
				}
			l10:
				add(ruleQuery, position9)
			}
			return true
		l8:
			position, tokenIndex = position8, tokenIndex8
			return false
		},
		/* 2 Term <- <(((('-' SetGenerator Action4) / (SetGenerator Action5) / (TextQuery Action6)) Action7) / ('(' Spacing? Query Spacing? ')' Action8))> */
		func() bool {
			position22, tokenIndex22 := position, tokenIndex
			{
				position23 := position
				{
					position24, tokenIndex24 := position, tokenIndex
					{
						position26, tokenIndex26 := position, tokenIndex
						if buffer[position] != rune('-') {
							goto l27
						}
						position++
						if !_rules[ruleSetGenerator]() {
							goto l27
						}
						{
							add(ruleAction4, position)
						}
						goto l26
					l27:
						position, tokenIndex = position26, tokenIndex26
						if !_rules[ruleSetGenerator]() {
							goto l29
						}
						{
							add(ruleAction5, position)
						}
						goto l26
					l29:
						position, tokenIndex = position26, tokenIndex26
						if !_rules[ruleTextQuery]() {
							goto l25
						}
						{
							add(ruleAction6, position)
						}
					}
				l26:
					{
						add(ruleAction7, position)
					}
					goto l24
				l25:
					position, tokenIndex = position24, tokenIndex24
					if buffer[position] != rune('(') {
						goto l22
					}
					position++
					{
						position33, tokenIndex33 := position, tokenIndex
						if !_rules[ruleSpacing]() {
							goto l33
						}
						goto l34
					l33:
						position, tokenIndex = position33, tokenIndex33
					}
				l34:
					if !_rules[ruleQuery]() {
						goto l22
					}
					{
						position35, tokenIndex35 := position, tokenIndex
						if !_rules[ruleSpacing]() {
							goto l35
						}
						goto l36
					l35:
						position, tokenIndex = position35, tokenIndex35
					}
				l36:
					if buffer[position] != rune(')') {
						goto l22
					}
					position++
					{
						add(ruleAction8, position)
					}
				}
			l24:
				add(ruleTerm, position23)
			}
			return true
		l22:
			position, tokenIndex = position22, tokenIndex22
			return false
		},
		/* 3 TextQuery <- <(QuotedText / Text)> */
		func() bool {
			position38, tokenIndex38 := position, tokenIndex
			{
				position39 := position
				{
					position40, tokenIndex40 := position, tokenIndex
					{
						position42 := position
						if buffer[position] != rune('"') {
							goto l41
						}
						position++
						{
							position43 := position
						l44:
							{
								position45, tokenIndex45 := position, tokenIndex
								{
									position46, tokenIndex46 := position, tokenIndex
									{
										position48, tokenIndex48 := position, tokenIndex
										{
											switch buffer[position] {
											case '\t':
												if buffer[position] != rune('\t') {
													goto l48
												}
												position++
											case '\r':
												if buffer[position] != rune('\r') {
													goto l48
												}
												position++
											case '\n':
												if buffer[position] != rune('\n') {
													goto l48
												}
												position++
											default:
												if buffer[position] != rune('"') {
													goto l48
												}
												position++
											}
										}

										goto l47
									l48:
										position, tokenIndex = position48, tokenIndex48
									}
									if !matchDot() {
										goto l47
									}
									goto l46
								l47:
									position, tokenIndex = position46, tokenIndex46
									if buffer[position] != rune('\\') {
										goto l45
									}
									position++
									if buffer[position] != rune('"') {
										goto l45
									}
									position++
								}
							l46:
								goto l44
							l45:
								position, tokenIndex = position45, tokenIndex45
							}
							add(rulePegText, position43)
						}
						if buffer[position] != rune('"') {
							goto l41
						}
						position++
						{
							add(ruleAction20, position)
						}
						add(ruleQuotedText, position42)
					}
					goto l40
				l41:
					position, tokenIndex = position40, tokenIndex40
					{
						position51 := position
						{
							position52 := position
							{
								position55, tokenIndex55 := position, tokenIndex
								{
									switch buffer[position] {
									case '\t':
										if buffer[position] != rune('\t') {
											goto l55
										}
										position++
									case '\r':
										if buffer[position] != rune('\r') {
											goto l55
										}
										position++
									case '\n':
										if buffer[position] != rune('\n') {
											goto l55
										}
										position++
									case ' ':
										if buffer[position] != rune(' ') {
											goto l55
										}
										position++
									case ')':
										if buffer[position] != rune(')') {
											goto l55
										}
										position++
									case '(':
										if buffer[position] != rune('(') {
											goto l55
										}
										position++
									case '=':
										if buffer[position] != rune('=') {
											goto l55
										}
										position++
									case '~':
										if buffer[position] != rune('~') {
											goto l55
										}
										position++
									case ':':
										if buffer[position] != rune(':') {
											goto l55
										}
										position++
									case '>':
										if buffer[position] != rune('>') {
											goto l55
										}
										position++
									case '<':
										if buffer[position] != rune('<') {
											goto l55
										}
										position++
									default:
										if buffer[position] != rune('"') {
											goto l55
										}
										position++
									}
								}

								goto l38
							l55:
								position, tokenIndex = position55, tokenIndex55
							}
							if !matchDot() {
								goto l38
							}
						l53:
							{
								position54, tokenIndex54 := position, tokenIndex
								{
									position57, tokenIndex57 := position, tokenIndex
									{
										switch buffer[position] {
										case '\t':
											if buffer[position] != rune('\t') {
												goto l57
											}
											position++
										case '\r':
											if buffer[position] != rune('\r') {
												goto l57
											}
											position++
										case '\n':
											if buffer[position] != rune('\n') {
												goto l57
											}
											position++
										case ' ':
											if buffer[position] != rune(' ') {
												goto l57
											}
											position++
										case ')':
											if buffer[position] != rune(')') {
												goto l57
											}
											position++
										case '(':
											if buffer[position] != rune('(') {
												goto l57
											}
											position++
										case '=':
											if buffer[position] != rune('=') {
												goto l57
											}
											position++
										case '~':
											if buffer[position] != rune('~') {
												goto l57
											}
											position++
										case ':':
											if buffer[position] != rune(':') {
												goto l57
											}
											position++
										case '>':
											if buffer[position] != rune('>') {
												goto l57
											}
											position++
										case '<':
											if buffer[position] != rune('<') {
												goto l57
											}
											position++
										default:
											if buffer[position] != rune('"') {
												goto l57
											}
											position++
										}
									}

									goto l54
								l57:
									position, tokenIndex = position57, tokenIndex57
								}
								if !matchDot() {
									goto l54
								}
								goto l53
							l54:
								position, tokenIndex = position54, tokenIndex54
							}
							add(rulePegText, position52)
						}
						{
							add(ruleAction21, position)
						}
						add(ruleText, position51)
					}
				}
			l40:
				add(ruleTextQuery, position39)
			}
			return true
		l38:
			position, tokenIndex = position38, tokenIndex38
			return false
		},
		/* 4 SetGenerator <- <(TextQuery Action9 GeneratorBinaryOperator TextQuery Action10)> */
		func() bool {
			position60, tokenIndex60 := position, tokenIndex
			{
				position61 := position
				if !_rules[ruleTextQuery]() {
					goto l60
				}
				{
					add(ruleAction9, position)
				}
				{
					position63 := position
					{
						position64, tokenIndex64 := position, tokenIndex
						if buffer[position] != rune('<') {
							goto l65
						}
						position++
						if buffer[position] != rune('=') {
							goto l65
						}
						position++
						{
							add(ruleAction14, position)
						}
						goto l64
					l65:
						position, tokenIndex = position64, tokenIndex64
						if buffer[position] != rune('>') {
							goto l67
						}
						position++
						if buffer[position] != rune('=') {
							goto l67
						}
						position++
						{
							add(ruleAction16, position)
						}
						goto l64
					l67:
						position, tokenIndex = position64, tokenIndex64
						{
							switch buffer[position] {
							case '~':
								if buffer[position] != rune('~') {
									goto l60
								}
								position++
								{
									add(ruleAction19, position)
								}
							case '=':
								if buffer[position] != rune('=') {
									goto l60
								}
								position++
								{
									add(ruleAction18, position)
								}
							case '>':
								if buffer[position] != rune('>') {
									goto l60
								}
								position++
								{
									add(ruleAction17, position)
								}
							case '<':
								if buffer[position] != rune('<') {
									goto l60
								}
								position++
								{
									add(ruleAction15, position)
								}
							default:
								if buffer[position] != rune(':') {
									goto l60
								}
								position++
								{
									add(ruleAction13, position)
								}
							}
						}

					}
				l64:
					add(ruleGeneratorBinaryOperator, position63)
				}
				if !_rules[ruleTextQuery]() {
					goto l60
				}
				{
					add(ruleAction10, position)
				}
				add(ruleSetGenerator, position61)
			}
			return true
		l60:
			position, tokenIndex = position60, tokenIndex60
			return false
		},
		/* 5 BinaryOperator <- <(('o' 'r' Action11) / ('a' 'n' 'd' Action12))> */
		nil,
		/* 6 GeneratorBinaryOperator <- <(('<' '=' Action14) / ('>' '=' Action16) / ((&('~') ('~' Action19)) | (&('=') ('=' Action18)) | (&('>') ('>' Action17)) | (&('<') ('<' Action15)) | (&(':') (':' Action13))))> */
		nil,
		/* 7 Spacing <- <((&('\n') '\n') | (&('\r') ('\r' '\n')) | (&('\t') '\t') | (&(' ') ' '))+> */
		func() bool {
			position78, tokenIndex78 := position, tokenIndex
			{
				position79 := position
				{
					switch buffer[position] {
					case '\n':
						if buffer[position] != rune('\n') {
							goto l78
						}
						position++
					case '\r':
						if buffer[position] != rune('\r') {
							goto l78
						}
						position++
						if buffer[position] != rune('\n') {
							goto l78
						}
						position++
					case '\t':
						if buffer[position] != rune('\t') {
							goto l78
						}
						position++
					default:
						if buffer[position] != rune(' ') {
							goto l78
						}
						position++
					}
				}

			l80:
				{
					position81, tokenIndex81 := position, tokenIndex
					{
						switch buffer[position] {
						case '\n':
							if buffer[position] != rune('\n') {
								goto l81
							}
							position++
						case '\r':
							if buffer[position] != rune('\r') {
								goto l81
							}
							position++
							if buffer[position] != rune('\n') {
								goto l81
							}
							position++
						case '\t':
							if buffer[position] != rune('\t') {
								goto l81
							}
							position++
						default:
							if buffer[position] != rune(' ') {
								goto l81
							}
							position++
						}
					}

					goto l80
				l81:
					position, tokenIndex = position81, tokenIndex81
				}
				add(ruleSpacing, position79)
			}
			return true
		l78:
			position, tokenIndex = position78, tokenIndex78
			return false
		},
		/* 8 QuotedText <- <('"' <((!((&('\t') '\t') | (&('\r') '\r') | (&('\n') '\n') | (&('"') '"')) .) / ('\\' '"'))*> '"' Action20)> */
		nil,
		/* 9 Text <- <(<(!((&('\t') '\t') | (&('\r') '\r') | (&('\n') '\n') | (&(' ') ' ') | (&(')') ')') | (&('(') '(') | (&('=') '=') | (&('~') '~') | (&(':') ':') | (&('>') '>') | (&('<') '<') | (&('"') '"')) .)+> Action21)> */
		nil,
		/* 10 EndOfFile <- <!.> */
		nil,
		/* 12 Action0 <- <{p.insertOperatorNode()}> */
		nil,
		/* 13 Action1 <- <{p.push(p.finaliseStack())}> */
		nil,
		/* 14 Action2 <- <{p.tempNode.BinaryOperator = Default_BinaryOperator; p.insertOperatorNode()}> */
		nil,
		/* 15 Action3 <- <{p.push(p.finaliseStack())}> */
		nil,
		/* 16 Action4 <- <{p.tempNode.Type = NodeType_SetGenerator; p.tempNode.SetGenerator.Negated = true}> */
		nil,
		/* 17 Action5 <- <{p.tempNode.Type = NodeType_SetGenerator}> */
		nil,
		/* 18 Action6 <- <{p.tempNode.Type = NodeType_Basic; p.tempNode.BasicQuery.Value = text}> */
		nil,
		/* 19 Action7 <- <{p.push(p.tempNode)}> */
		nil,
		/* 20 Action8 <- <{p.push(p.finaliseStack())}> */
		nil,
		/* 21 Action9 <- <{p.tempNode.SetGenerator.Key = text}> */
		nil,
		/* 22 Action10 <- <{p.tempNode.SetGenerator.Value = text}> */
		nil,
		/* 23 Action11 <- <{p.tempNode.BinaryOperator = BinaryOperator_Or}> */
		nil,
		/* 24 Action12 <- <{p.tempNode.BinaryOperator = BinaryOperator_And}> */
		nil,
		/* 25 Action13 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_Includes}> */
		nil,
		/* 26 Action14 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_LessThanEquals}> */
		nil,
		/* 27 Action15 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_LessThan}> */
		nil,
		/* 28 Action16 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_GreaterThanEquals}> */
		nil,
		/* 29 Action17 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_GreaterThan}> */
		nil,
		/* 30 Action18 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_Equals}> */
		nil,
		/* 31 Action19 <- <{p.tempNode.SetGenerator.GeneratorOperator = GeneratorOperator_NotEquals}> */
		nil,
		nil,
		/* 33 Action20 <- <{
		   output, err := UnescapeText(text)
		   if err != nil {
		     p.Err = errors.Join(fmt.Errorf("Cannot parse quoted string '%s'", text))
		     return
		   }

		   text = NormText(output)
		 }> */
		nil,
		/* 34 Action21 <- <{text = NormText(text)}> */
		nil,
	}
	p.rules = _rules
	return nil
}
