// Code generated by tygo. DO NOT EDIT.

//////////
// source: main.go

export const EnvVarPrefix = "RPG_BOOK_";
export const EnvVarCertificate = EnvVarPrefix + "CERTIFICATE";
export const EnvVarPort = EnvVarPrefix + "PORT";
