name: test 

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/workflows/shared/setup
      - name: Test
        shell: bash
        env:
          FUZZTIME: 5m
        run: make fuzz -j
