name: test 

on:
  pull_request:
    branches:
      - main
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/shared/setup
      - name: Test
        run: make test -j
